### ISSUE TITLE
Possible to generate new .elc file from auto-compile-save-mode

### ISSUE THREAD

**Issue by justbur** [tarsius/auto-compile#12]
Steps from `emacs -Q` and a blank file

1. load using something like

 ```elisp
 (add-to-list 'load-path "~/src/dash.el")
 (add-to-list 'load-path "~/src/packed")
 (add-to-list 'load-path "~/src/auto-compile")
 (require 'auto-compile)
 (auto-compile-on-save-mode 1)
 ```
2. add

 ```elisp
 (setq a
 ```

3. save and get an unmatched paren error
4. Fix it and save again

 ```elisp
 (setq a 1)
 ```
5. Now there is an .elc file where none existed before

I don't think this is intended, but I'm not sure.

Reference: https://github.com/syl20bnr/spacemacs/issues/3694

**Comment by tarsius** [comment]
Thanks a lot, I have seen this happening before, but could never figure out what was going on.

**Comment by justbur** [comment]
Thanks for the quick response
