### ISSUE TITLE
Autoload auto-compile-on-load-mode

### ISSUE THREAD

**Issue by LordYuuma** [tarsius/auto-compile#13]
Using an init file like
 
    (setq load-prefer-newer t)
    (package-initialize)
    (setq custom-file "/path/to/custom.el")
    (load custom-file)

and a custom file containing

    (custom-set-variables 
      '(auto-compile-on-load-mode t))

auto-compile will not be loaded. Setting `auto-compile-on-save-mode` to `t` using `Customize` fixes this, but I don't think byte-compiling on every small change is a good idea, when Emacs is still running and `eval-region` can take care of new changes.

There are a few ways of fixing this issue. One would be to require auto-compile via the REQUEST argument of `custom-set-variables`. In order to set this using `Customize` (and not directly touching the custom file), `:require` must be given.
The other would be to add an autoload cookie for `auto-compile-on-load-mode` as well. I don't really see a reason behind the inconsistency of having a cookie for one, but not the other, but that's just my opinion. A similar effect can be achieved by using `(custom-autoload 'auto-compile-on-load-mode "auto-compile" nil)` in the init file after `(package-initialize)`.
You can of course also combine these two the way for instance `yasnippet` does e.g. with `yas-global-mode`, which makes a lot of sense for globalized minor modes.

**Comment by tarsius** [comment]
If added the autoload cookie. But I still recommend loading the modes like this:

```lisp
;;; init.el --- user init file      -*- no-byte-compile: t -*-
(setq load-prefer-newer t)
(package-initialize)
(require 'auto-compile)
(auto-compile-on-load-mode)
(auto-compile-on-save-mode)
```
