### ISSUE TITLE
Why are the hooks installed locally?

### ISSUE THREAD

**Issue by Andersbakken** [tarsius/auto-compile#14]
It ends up stomping on my global hooks for after-save

**Comment by tarsius** [comment]
Which hooks? In the case of `magit-wip-after-save-local-mode` (the only one added to `after-save-hook`) it is because this is a enabled-in-certain-file-visiting-buffers hook, enabling it globally would not work.

**Comment by tarsius** [comment]
Wow wrong repository :-)

**Comment by tarsius** [comment]
Adding `auto-compile-byte-compile` to the local value of `after-save-hook` allows doing certain work only once (when determining whether `auto-compile-mode` should be turned on in a given buffer), instead of every time any buffer is saved.

Adding functions to the local value of a hook should not mess with your global value. If it does, then you are probably doing something wrong. Are you manipulating the hooks using something different from the official functions for doing so?

**Comment by Andersbakken** [comment]
:-)

It was the auto-compile package.

Anders

**Comment by Andersbakken** [comment]
It's not messing with my global ones but it causes my buffer to no longer
have any global hooks called.

E.g.

In my elisp buffer I now only have the byte-compile hook, not any of my
other after-save hooks.

I suppose it would work if I made sure that auto-compile-mode happens last.

Anders

**Comment by tarsius** [comment]
Adding a hook function to a hook variable should not remove any other hook functions:

```
(add-hook HOOK FUNCTION &optional APPEND LOCAL)

Add to the value of HOOK the function FUNCTION.
FUNCTION is not added if already present.
FUNCTION is added (if necessary) at the beginning of the hook list
unless the optional argument APPEND is non-nil, in which case
FUNCTION is added at the end.

The optional fourth argument, LOCAL, if non-nil, says to modify
the hook's buffer-local value rather than its global value.
This makes the hook buffer-local, and it makes t a member of the
buffer-local value.  That acts as a flag to run the hook
functions of the global value as well as in the local value.

HOOK should be a symbol, and FUNCTION may be any valid function.  If
HOOK is void, it is first set to nil.  If HOOK's value is a single
function, it is changed to a list of functions.
```

You'll have to provide more detailed steps to reproduce. And expect it will turn out that `auto-compile` isn't the problem.

Here is my value:

```
Its value is
(auto-compile-byte-compile diff-hl-update t magit-wip-commit-buffer-file)

Original value was nil
Local in buffer auto-compile.el; global value is 
(sml/generate-buffer-identification magit-after-save-refresh-status)
```

All hooks are run as expected.

**Comment by Andersbakken** [comment]
You're completely right. I misdiagnosed this. My bad.

Anders

**Comment by tarsius** [comment]
;-)
